runtime: nodejs18
service: default

handlers:
  # Serve static assets with long-term caching
  - url: /assets/(.*)
    static_files: dist/assets/\1
    upload: dist/assets/.*
    secure: always
    expiration: 1y

  # Serve index.html for root
  - url: /
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

  # Serve all other routes to index.html for SPA routing
  - url: /(.*)
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

# Ensure dist folder is included
skip_files:
  - ^(.*/)?\..*$
  - ^node_modules/.*$
  - ^src/.*$
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.bak$
